version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: test_app_docker_git_CiCd
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    volumes:
      - .:/app          # Mount source code for hot reload
      - /app/node_modules  # Prevent overwriting node_modules
