version: '3.8'
services:
  # Development app with hot reload
  app-dev:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app-dev
    ports:
      - "3000:3000"
      - "9229:9229"  # Debug port
    environment:
      - NODE_ENV=development
      - DEBUG=app:*
    volumes:
      - .:/usr/src/app          # Mount source code for hot reload
      - /usr/src/app/node_modules  # Prevent overwriting node_modules


volumes:
  dev_data: