global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['172.16.14.75:3000']

  # - job_name: 'my_application'
  #   static_configs:
  #     - targets: ['localhost:8080']
  #       labels:
  #         environment: 'production'
  #         team: 'backend'

  # - job_name: 'database_exporter'
  #   static_configs:
  #     - targets: ['localhost:5432']
  #       labels:
  #         environment: 'production'
  #         team: 'database'
